import type { Request, Response, NextFunction } from 'express';
import { getServerConfig } from './config';

export function securityHeaders(req: Request, res: Response, next: NextFunction): void {
  const isProduction = getServerConfig().nodeEnv === 'production';
  res.setHeader('X-Content-Type-Options', 'nosniff');
  res.setHeader('Referrer-Policy', 'strict-origin-when-cross-origin');
  res.setHeader('Cross-Origin-Opener-Policy', 'same-origin-allow-popups');
  if (isProduction && getServerConfig().frameAncestors === "'self'") res.setHeader('X-Frame-Options', 'SAMEORIGIN');
  res.setHeader('Permissions-Policy', 'camera=(), microphone=(), geolocation=(), payment=()');
  if (isProduction) {
    res.setHeader('Strict-Transport-Security', 'max-age=31536000; includeSubDomains');
  }
  // Keep the policy compatible with Vite dev, data/blob image previews, inline CSS generated by the app,
  // and Gemini requests performed from the browser/server without enabling arbitrary script origins.
  const connectSources = isProduction ? "'self' https://generativelanguage.googleapis.com" : "'self' ws: wss: http: https:";
  res.setHeader('Content-Security-Policy', [
    "default-src 'self'",
    "script-src 'self'",
    "style-src 'self' 'unsafe-inline'",
    "img-src 'self' data: blob:",
    "font-src 'self' data:",
    `connect-src ${connectSources}`,
    "object-src 'none'",
    "base-uri 'self'",
    `frame-ancestors ${getServerConfig().frameAncestors}`,
    "form-action 'self'",
    "worker-src 'self' blob:",
  ].join('; '));
  if (req.path === '/api/health' || req.path === '/api/health/live' || req.path === '/api/health/ready') {
    res.setHeader('Cache-Control', 'no-store');
  }
  next();
}
