export const COPY = {
  hero: {
    title: 'Stop wasting hours between courses.',
    question: 'Have you ever had a course at 10 AM and your next one was at 1 PM?',
    problem: 'That’s 3 hours stuck on campus, waiting around for your next class.',
    empathy: 'Nobody wants to spend their day like that.',
    why: 'Gadwal finds you a schedule that actually makes sense.',
    primary: 'Find my best schedule',
    guide: 'Learn how',
  },
  how: {
    title: 'How Gadwal works',
    intro: 'You choose the courses you want.',
    sections: 'Each course can have multiple sections with different days and times.',
    combinations: 'That means there can be hundreds or even thousands of possible combinations.',
    manual: 'You could try to test them yourself...',
    handoff: 'Or let Gadwal do it for you.',
    searches: 'Gadwal checks the possible combinations and finds schedules with:',
    fewerDays: 'fewer days',
    lessGap: 'less gap time',
    noConflicts: 'no course conflicts',
    chooseBest: 'Then you choose the schedule you like best.',
    startAction: 'Start adding courses',
  },
  promise: {
    title: 'Our Promise',
    core: 'Gadwal works with the real options your university gives you.',
    available: 'You choose the courses you want, and Gadwal looks through the sections available for them.',
    cannot: "Gadwal can’t create new sections, change meeting times, or add courses that aren’t available.",
    startAction: 'Start adding courses',
    exampleHeading: 'For example',
    exampleIntro: 'Say you want to take 4 courses and you’d like to be on campus 4 days a week.',
    exampleSpread: 'But the sections available for those courses are spread across 6 days.',
    exampleImpossible: 'Gadwal can’t magically turn that into a 4-day schedule.',
    exampleTruth: 'It can only work with the sections that actually exist.',
    capabilityHeading: 'Here’s what Gadwal can do',
    capabilityIntro: 'You might choose your sections manually and end up with:',
    gapChange: 'In some cases, that could mean going from 11 hours of gaps to 5.',
    sectionsExist: 'But this only works if those better sections and combinations actually exist.',
    impossibleHeading: 'What if the perfect schedule isn’t possible?',
    okay: 'That’s okay.',
    bestAvailable: 'Gadwal will show you the best combinations it can find from the sections available to you.',
    maybeNoImprovement: 'Or you might not see much improvement.',
    depends: 'It all depends on the sections your university offers.',
    screenshotsHeading: 'Your screenshots matter',
    screenshotSource: 'Gadwal can only use the information you give it.',
    screenshotMissing: 'If a section isn’t in your screenshots, Gadwal can’t consider it.',
    screenshotFresh: 'Make sure your screenshots are clear and up to date.',
    screenshotUpdate: 'If your university changes a section, day, or time later, update your screenshots so Gadwal has the latest information.',
    finalHeading: 'One last thing',
    finalNoRegister: 'Gadwal doesn’t register you for courses or change anything in your university portal.',
    finalSearchOnly: 'It only searches and compares the options you provide.',
    finalTruth: 'Your university portal is the final source of truth.',
    finalYouChoose: 'You choose the courses.',
    finalSearch: 'Gadwal does the searching.',
    finalDecision: 'You make the final decision.',
    finalTrust: 'We’ll show you what’s actually possible. We won’t invent a better schedule just to make the result look better.',
  },
  trust: {
    aiNotice: 'Using screenshots? We read the course names, sections, days, and times for you. The image is sent to Gadwal for that step. Check what we found before building.',
    privacyLink: 'How your data is handled',
    review: 'Check the course names, sections, days, times, and credits before building.',
  },
  flow: {
    screenshotTab: 'Use screenshots',
    screenshotHelp: 'Best when you want it fast.',
    manualTab: 'Enter courses',
    manualHelp: 'Add a course yourself when a screenshot does not have it.',
  },
  completeness: {
    exhaustive: 'We checked the full search that fit within the search limits.',
    sampled: 'We checked a smaller group of course combinations. Other valid schedules may exist.',
    capped: 'The search hit a work limit before every combination could be checked. Other valid schedules may exist.',
    cancelled: 'The search stopped early. These are the schedules found before it stopped.',
  },
  empty: {
    resultsTitle: 'We couldn’t find a schedule that fits these choices.',
    resultsBody: 'Try changing one of your course choices or preferences, then build again.',
  },
  demo: {
    title: 'Screenshot guide',
    subtitle: '',
    howTitle: 'How to take your screenshots',
    chapter1: 'Part 1 · Get ready',
    chapter1Label: 'PART 1 · GET READY',
    chapter1Title: 'Get ready',
    chapter1Purpose: 'Get into the correct place and clear your schedule.',
    step1Title: '1. Open Advising',
    step1Body: 'Go to your student portal and click Advising.',
    step2Title: '2. Clear your schedule',
    step2Body: 'Drop/remove all courses currently in your schedule.',
    step2Note: 'Start with an empty schedule so you can see all available options.',
    chapter2: 'Part 2 · Capture',
    chapter2Label: 'PART 2 · CAPTURE',
    chapter2Title: 'Capture',
    chapter2Purpose: 'Capture every available section with a clear screenshot.',
    step3Title: '3. Open each course',
    step3Body1: 'Click Add Courses, then select a course to see its available options.',
    step3Body2: 'You may see one or multiple options, such as New07 or New09.',
    step3Rule: 'Only choose courses you’re actually willing to take.',
    step4Title: '4. Take a screenshot',
    step4Body: 'Click each available option one at a time and take a screenshot. For example, Nutrition has just one option, NUT10102-MCM, so take one screenshot, click Back, and move on to your next course.',
    step4ChecklistTitle: 'Make sure it shows:',
    step5Title: '5. Repeat for every course',
    step5Body1: 'Screenshot every available option for the courses you chose.',
    step5Body2: 'For example, if Financial Management has New07 and New09, take one screenshot of each.',
    step5Body3: 'Go back to your course list and repeat for your other courses.',
    step6Title: '6. Summary',
    step6Body: 'Review the screenshots you gathered across all your courses.',
    chapter3: 'Part 3 · Finish',
    chapter3Label: 'PART 3 · FINISH',
    chapter3Title: 'Finish',
    step7Title: '7. Upload your screenshots',
    step7Body: 'Once you’ve captured all the options you want, upload your screenshots to Gadwal.',
    step7Ending: 'That’s it. Gadwal checks the available combinations within its search limits and shows the best schedules it finds.',
    tipsTitle: 'Quick tips',
  },
} as const;

export type SearchCompletenessCopy = keyof typeof COPY.completeness;
